name: Smart Building Automation
description: Smart building system prototype that can adjust the brightness of indoor lights through web application.
date: 2021-05-28
stack:
  - Express
  - InfluxDB
  - ESP32
thumbnail: light.jpeg
images:
  - src: light.jpeg
    alt: Light control page
